server:
  port: 9527

spring:
  application:
    name: microservicecloud-zuul-gateway

#路由配置
zuul:
  #ignored-services: microservicecloud-dept
  prefix: /example        #设置前缀
  ignored-services: "*"   #设置多路径
  routes:
    mydept.serviceId: microservicecloud-dept
    mydept.path: /mydept/**

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
  instance:
    instance-id: gateway-9527.com
    prefer-ip-address: true


info:
  app.name: example-microcloud
  company.name: www.example.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
